// Mocks generated by Mockito 5.4.4 from annotations
// in student_management/test/presentation/views/dashboard/widgets/school_admin/school_admin_dashboard_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:student_management/presentation/views/dashboard/data/models/res/school_admin/dashboard_stats_model.dart'
    as _i2;
import 'package:student_management/presentation/views/dashboard/data/repositories/school_admin_dashboard_repository.dart'
    as _i4;
import 'package:student_management/presentation/views/fee/data/models/fee_payment_model.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTenantStatistics_0 extends _i1.SmartFake
    implements _i2.TenantStatistics {
  _FakeTenantStatistics_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCollectionReport_1 extends _i1.SmartFake
    implements _i3.CollectionReport {
  _FakeCollectionReport_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SchoolAdminDashboardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSchoolAdminDashboardRepository extends _i1.Mock
    implements _i4.SchoolAdminDashboardRepository {
  MockSchoolAdminDashboardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.TenantStatistics> getTenantStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getTenantStatistics,
          [],
        ),
        returnValue:
            _i5.Future<_i2.TenantStatistics>.value(_FakeTenantStatistics_0(
          this,
          Invocation.method(
            #getTenantStatistics,
            [],
          ),
        )),
      ) as _i5.Future<_i2.TenantStatistics>);

  @override
  _i5.Future<_i3.CollectionReport> getFeeCollectionReport() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeeCollectionReport,
          [],
        ),
        returnValue:
            _i5.Future<_i3.CollectionReport>.value(_FakeCollectionReport_1(
          this,
          Invocation.method(
            #getFeeCollectionReport,
            [],
          ),
        )),
      ) as _i5.Future<_i3.CollectionReport>);

  @override
  _i5.Future<int> getPendingLeaveCount() => (super.noSuchMethod(
        Invocation.method(
          #getPendingLeaveCount,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
}
