// Mocks generated by Mockito 5.4.4 from annotations
// in student_management/test/presentation/views/dashboard/presentation/manager/profile_management_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:student_management/core/services/storage_service/storage_contract/storage_contract.dart'
    as _i8;
import 'package:student_management/presentation/views/dashboard/data/models/req/profile_fetch_req.dart'
    as _i5;
import 'package:student_management/presentation/views/dashboard/data/models/req/profile_update_req.dart'
    as _i7;
import 'package:student_management/presentation/views/dashboard/domain/use_cases/profile_fetch_use_case.dart'
    as _i3;
import 'package:student_management/presentation/views/dashboard/domain/use_cases/profile_update_use_case.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileFetchUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileFetchUseCase extends _i1.Mock
    implements _i3.ProfileFetchUseCase {
  MockProfileFetchUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response<dynamic>> call(
          {required _i5.ProfileFetchRequest? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #call,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);
}

/// A class which mocks [ProfileUpdateUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileUpdateUseCase extends _i1.Mock
    implements _i6.ProfileUpdateUseCase {
  MockProfileUpdateUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response<dynamic>> call(
          {required _i7.ProfileUpdateRequest? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #call,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);
}

/// A class which mocks [StorageStrategy].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageStrategy extends _i1.Mock implements _i8.StorageStrategy {
  MockStorageStrategy() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> write(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<T?> read<T>(String? key) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [key],
        ),
        returnValue: _i4.Future<T?>.value(),
      ) as _i4.Future<T?>);

  @override
  T? readSync<T>(String? key) => (super.noSuchMethod(Invocation.method(
        #readSync,
        [key],
      )) as T?);

  @override
  _i4.Future<void> delete(String? key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
