// Mocks generated by Mockito 5.4.4 from annotations
// in student_management/test/presentation/views/class_mgmt/presentation/manager/class_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:student_management/presentation/views/class_mgmt/data/models/class_model.dart'
    as _i2;
import 'package:student_management/presentation/views/class_mgmt/data/repositories/class_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSchoolClassResponse_0 extends _i1.SmartFake
    implements _i2.SchoolClassResponse {
  _FakeSchoolClassResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSectionResponse_1 extends _i1.SmartFake
    implements _i2.SectionResponse {
  _FakeSectionResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ClassRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassRepository extends _i1.Mock implements _i3.ClassRepository {
  MockClassRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.SchoolClassResponse>> getAllClasses() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllClasses,
          [],
        ),
        returnValue: _i4.Future<List<_i2.SchoolClassResponse>>.value(
            <_i2.SchoolClassResponse>[]),
      ) as _i4.Future<List<_i2.SchoolClassResponse>>);

  @override
  _i4.Future<_i2.SchoolClassResponse> getClassById(String? classId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassById,
          [classId],
        ),
        returnValue: _i4.Future<_i2.SchoolClassResponse>.value(
            _FakeSchoolClassResponse_0(
          this,
          Invocation.method(
            #getClassById,
            [classId],
          ),
        )),
      ) as _i4.Future<_i2.SchoolClassResponse>);

  @override
  _i4.Future<_i2.SchoolClassResponse> createClass(
          _i2.CreateClassRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createClass,
          [request],
        ),
        returnValue: _i4.Future<_i2.SchoolClassResponse>.value(
            _FakeSchoolClassResponse_0(
          this,
          Invocation.method(
            #createClass,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.SchoolClassResponse>);

  @override
  _i4.Future<_i2.SectionResponse> createSection(
          _i2.CreateSectionRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSection,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.SectionResponse>.value(_FakeSectionResponse_1(
          this,
          Invocation.method(
            #createSection,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.SectionResponse>);

  @override
  _i4.Future<List<_i2.SectionResponse>> getSectionsByClass(String? classId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSectionsByClass,
          [classId],
        ),
        returnValue: _i4.Future<List<_i2.SectionResponse>>.value(
            <_i2.SectionResponse>[]),
      ) as _i4.Future<List<_i2.SectionResponse>>);

  @override
  _i4.Future<List<_i2.SectionResponse>> createBulkSections(
    String? classId,
    List<_i2.CreateSectionRequest>? sections,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBulkSections,
          [
            classId,
            sections,
          ],
        ),
        returnValue: _i4.Future<List<_i2.SectionResponse>>.value(
            <_i2.SectionResponse>[]),
      ) as _i4.Future<List<_i2.SectionResponse>>);
}
