// Mocks generated by Mockito 5.4.4 from annotations
// in student_management/test/presentation/views/attendance/presentation/manager/attendance_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:student_management/presentation/views/attendance/data/models/attendance_model.dart'
    as _i2;
import 'package:student_management/presentation/views/attendance/data/repositories/attendance_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAttendancePercentage_0 extends _i1.SmartFake
    implements _i2.AttendancePercentage {
  _FakeAttendancePercentage_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AttendanceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAttendanceRepository extends _i1.Mock
    implements _i3.AttendanceRepository {
  MockAttendanceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> markBulkAttendance(_i2.MarkAttendanceRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #markBulkAttendance,
          [request],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.AttendanceResponse>> getAttendanceByClass(
    String? classId,
    String? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAttendanceByClass,
          [
            classId,
            date,
          ],
        ),
        returnValue: _i4.Future<List<_i2.AttendanceResponse>>.value(
            <_i2.AttendanceResponse>[]),
      ) as _i4.Future<List<_i2.AttendanceResponse>>);

  @override
  _i4.Future<List<_i2.AttendanceResponse>> getStudentAttendance(
    String? studentId, {
    int? page,
    int? size,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStudentAttendance,
          [studentId],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i4.Future<List<_i2.AttendanceResponse>>.value(
            <_i2.AttendanceResponse>[]),
      ) as _i4.Future<List<_i2.AttendanceResponse>>);

  @override
  _i4.Future<List<_i2.AttendanceResponse>> getStudentAttendanceByDateRange(
    String? studentId,
    String? startDate,
    String? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStudentAttendanceByDateRange,
          [
            studentId,
            startDate,
            endDate,
          ],
        ),
        returnValue: _i4.Future<List<_i2.AttendanceResponse>>.value(
            <_i2.AttendanceResponse>[]),
      ) as _i4.Future<List<_i2.AttendanceResponse>>);

  @override
  _i4.Future<_i2.AttendancePercentage> getStudentAttendancePercentage(
          String? studentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStudentAttendancePercentage,
          [studentId],
        ),
        returnValue: _i4.Future<_i2.AttendancePercentage>.value(
            _FakeAttendancePercentage_0(
          this,
          Invocation.method(
            #getStudentAttendancePercentage,
            [studentId],
          ),
        )),
      ) as _i4.Future<_i2.AttendancePercentage>);

  @override
  _i4.Future<List<_i2.AttendanceResponse>> getAttendanceByDate(String? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAttendanceByDate,
          [date],
        ),
        returnValue: _i4.Future<List<_i2.AttendanceResponse>>.value(
            <_i2.AttendanceResponse>[]),
      ) as _i4.Future<List<_i2.AttendanceResponse>>);
}
