// Mocks generated by Mockito 5.4.4 from annotations
// in student_management/test/presentation/views/teacher/presentation/manager/teacher_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:student_management/core/base/paginated_response.dart' as _i2;
import 'package:student_management/presentation/views/teacher/data/models/teacher_model.dart'
    as _i3;
import 'package:student_management/presentation/views/teacher/data/repositories/teacher_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaginatedResponse_0<T> extends _i1.SmartFake
    implements _i2.PaginatedResponse<T> {
  _FakePaginatedResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTeacherResponse_1 extends _i1.SmartFake
    implements _i3.TeacherResponse {
  _FakeTeacherResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TeacherRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTeacherRepository extends _i1.Mock implements _i4.TeacherRepository {
  MockTeacherRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.PaginatedResponse<_i3.TeacherResponse>> getAllTeachers({
    int? page,
    int? size,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllTeachers,
          [],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue:
            _i5.Future<_i2.PaginatedResponse<_i3.TeacherResponse>>.value(
                _FakePaginatedResponse_0<_i3.TeacherResponse>(
          this,
          Invocation.method(
            #getAllTeachers,
            [],
            {
              #page: page,
              #size: size,
            },
          ),
        )),
      ) as _i5.Future<_i2.PaginatedResponse<_i3.TeacherResponse>>);

  @override
  _i5.Future<_i3.TeacherResponse> getTeacherById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeacherById,
          [id],
        ),
        returnValue:
            _i5.Future<_i3.TeacherResponse>.value(_FakeTeacherResponse_1(
          this,
          Invocation.method(
            #getTeacherById,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.TeacherResponse>);

  @override
  _i5.Future<_i3.TeacherResponse> getTeacherByEmployeeId(String? employeeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeacherByEmployeeId,
          [employeeId],
        ),
        returnValue:
            _i5.Future<_i3.TeacherResponse>.value(_FakeTeacherResponse_1(
          this,
          Invocation.method(
            #getTeacherByEmployeeId,
            [employeeId],
          ),
        )),
      ) as _i5.Future<_i3.TeacherResponse>);

  @override
  _i5.Future<_i3.TeacherResponse> createTeacher(
          _i3.CreateTeacherRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTeacher,
          [request],
        ),
        returnValue:
            _i5.Future<_i3.TeacherResponse>.value(_FakeTeacherResponse_1(
          this,
          Invocation.method(
            #createTeacher,
            [request],
          ),
        )),
      ) as _i5.Future<_i3.TeacherResponse>);

  @override
  _i5.Future<_i3.TeacherResponse> updateTeacher(
    String? id,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTeacher,
          [
            id,
            updates,
          ],
        ),
        returnValue:
            _i5.Future<_i3.TeacherResponse>.value(_FakeTeacherResponse_1(
          this,
          Invocation.method(
            #updateTeacher,
            [
              id,
              updates,
            ],
          ),
        )),
      ) as _i5.Future<_i3.TeacherResponse>);

  @override
  _i5.Future<void> deleteTeacher(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTeacher,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
