// Mocks generated by Mockito 5.4.4 from annotations
// in student_management/test/presentation/views/timetable/presentation/manager/timetable_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:student_management/presentation/views/timetable/data/models/period_model.dart'
    as _i2;
import 'package:student_management/presentation/views/timetable/data/models/timetable_entry_model.dart'
    as _i3;
import 'package:student_management/presentation/views/timetable/data/repositories/timetable_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePeriodResponse_0 extends _i1.SmartFake
    implements _i2.PeriodResponse {
  _FakePeriodResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTimetableEntryResponse_1 extends _i1.SmartFake
    implements _i3.TimetableEntryResponse {
  _FakeTimetableEntryResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TimetableRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimetableRepository extends _i1.Mock
    implements _i4.TimetableRepository {
  MockTimetableRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.PeriodResponse>> getPeriods() => (super.noSuchMethod(
        Invocation.method(
          #getPeriods,
          [],
        ),
        returnValue:
            _i5.Future<List<_i2.PeriodResponse>>.value(<_i2.PeriodResponse>[]),
      ) as _i5.Future<List<_i2.PeriodResponse>>);

  @override
  _i5.Future<List<_i2.PeriodResponse>> getActivePeriods() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivePeriods,
          [],
        ),
        returnValue:
            _i5.Future<List<_i2.PeriodResponse>>.value(<_i2.PeriodResponse>[]),
      ) as _i5.Future<List<_i2.PeriodResponse>>);

  @override
  _i5.Future<_i2.PeriodResponse> createPeriod(_i2.PeriodRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPeriod,
          [request],
        ),
        returnValue: _i5.Future<_i2.PeriodResponse>.value(_FakePeriodResponse_0(
          this,
          Invocation.method(
            #createPeriod,
            [request],
          ),
        )),
      ) as _i5.Future<_i2.PeriodResponse>);

  @override
  _i5.Future<_i2.PeriodResponse> updatePeriod(
    String? id,
    _i2.PeriodRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePeriod,
          [
            id,
            request,
          ],
        ),
        returnValue: _i5.Future<_i2.PeriodResponse>.value(_FakePeriodResponse_0(
          this,
          Invocation.method(
            #updatePeriod,
            [
              id,
              request,
            ],
          ),
        )),
      ) as _i5.Future<_i2.PeriodResponse>);

  @override
  _i5.Future<void> deletePeriod(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePeriod,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.TimetableEntryResponse> createEntry(
          _i3.TimetableEntryRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEntry,
          [request],
        ),
        returnValue: _i5.Future<_i3.TimetableEntryResponse>.value(
            _FakeTimetableEntryResponse_1(
          this,
          Invocation.method(
            #createEntry,
            [request],
          ),
        )),
      ) as _i5.Future<_i3.TimetableEntryResponse>);

  @override
  _i5.Future<List<_i3.TimetableEntryResponse>> getClassTimetable(
          String? classId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassTimetable,
          [classId],
        ),
        returnValue: _i5.Future<List<_i3.TimetableEntryResponse>>.value(
            <_i3.TimetableEntryResponse>[]),
      ) as _i5.Future<List<_i3.TimetableEntryResponse>>);

  @override
  _i5.Future<List<_i3.TimetableEntryResponse>> getTeacherTimetable(
          String? teacherId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTeacherTimetable,
          [teacherId],
        ),
        returnValue: _i5.Future<List<_i3.TimetableEntryResponse>>.value(
            <_i3.TimetableEntryResponse>[]),
      ) as _i5.Future<List<_i3.TimetableEntryResponse>>);

  @override
  _i5.Future<Map<String, List<_i3.TimetableEntryResponse>>>
      getClassWeeklyTimetable(String? classId) => (super.noSuchMethod(
            Invocation.method(
              #getClassWeeklyTimetable,
              [classId],
            ),
            returnValue:
                _i5.Future<Map<String, List<_i3.TimetableEntryResponse>>>.value(
                    <String, List<_i3.TimetableEntryResponse>>{}),
          ) as _i5.Future<Map<String, List<_i3.TimetableEntryResponse>>>);

  @override
  _i5.Future<Map<String, List<_i3.TimetableEntryResponse>>>
      getTeacherWeeklyTimetable(String? teacherId) => (super.noSuchMethod(
            Invocation.method(
              #getTeacherWeeklyTimetable,
              [teacherId],
            ),
            returnValue:
                _i5.Future<Map<String, List<_i3.TimetableEntryResponse>>>.value(
                    <String, List<_i3.TimetableEntryResponse>>{}),
          ) as _i5.Future<Map<String, List<_i3.TimetableEntryResponse>>>);

  @override
  _i5.Future<List<_i3.TimetableEntryResponse>> getClassDayTimetable(
    String? classId,
    String? day,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getClassDayTimetable,
          [
            classId,
            day,
          ],
        ),
        returnValue: _i5.Future<List<_i3.TimetableEntryResponse>>.value(
            <_i3.TimetableEntryResponse>[]),
      ) as _i5.Future<List<_i3.TimetableEntryResponse>>);

  @override
  _i5.Future<_i3.TimetableEntryResponse> updateEntry(
    String? id,
    _i3.TimetableEntryRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEntry,
          [
            id,
            request,
          ],
        ),
        returnValue: _i5.Future<_i3.TimetableEntryResponse>.value(
            _FakeTimetableEntryResponse_1(
          this,
          Invocation.method(
            #updateEntry,
            [
              id,
              request,
            ],
          ),
        )),
      ) as _i5.Future<_i3.TimetableEntryResponse>);

  @override
  _i5.Future<void> deleteEntry(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntry,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
