// Mocks generated by Mockito 5.4.4 from annotations
// in student_management/test/presentation/my_app/presentation/manager/app_config_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:student_management/core/base/base_client/no_param.dart' as _i5;
import 'package:student_management/presentation/my_app/domain/repo/app_config_repo.dart'
    as _i6;
import 'package:student_management/presentation/my_app/domain/use_case/get_app_config_use_case.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FetchAppConfigUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchAppConfigUseCase extends _i1.Mock
    implements _i3.FetchAppConfigUseCase {
  MockFetchAppConfigUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response<dynamic>> call({required _i5.NoParam? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #call,
            [],
            {#params: params},
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);
}

/// A class which mocks [AppConfigRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppConfigRepo extends _i1.Mock implements _i6.AppConfigRepo {
  MockAppConfigRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response<dynamic>> getAppConfig() => (super.noSuchMethod(
        Invocation.method(
          #getAppConfig,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #getAppConfig,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> getTenantSettings() => (super.noSuchMethod(
        Invocation.method(
          #getTenantSettings,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #getTenantSettings,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> updateTenantSettings(
          Map<String, dynamic>? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTenantSettings,
          [settings],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #updateTenantSettings,
            [settings],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);
}
