enum AppCountry {
  afghanistan("AF", "Afghanistan", "🇦🇫", "+93"),
  albania("AL", "Albania", "🇦🇱", "+355"),
  algeria("DZ", "Algeria", "🇩🇿", "+213"),
  andorra("AD", "Andorra", "🇦🇩", "+376"),
  angola("AO", "Angola", "🇦🇴", "+244"),
  antiguaBarbuda("AG", "Antigua and Barbuda", "🇦🇬", "+1-268"),
  argentina("AR", "Argentina", "🇦🇷", "+54"),
  armenia("AM", "Armenia", "🇦🇲", "+374"),
  australia("AU", "Australia", "🇦🇺", "+61"),
  austria("AT", "Austria", "🇦🇹", "+43"),
  azerbaijan("AZ", "Azerbaijan", "🇦🇿", "+994"),
  bahamas("BS", "Bahamas", "🇧🇸", "+1-242"),
  bahrain("BH", "Bahrain", "🇧🇭", "+973"),
  bangladesh("BD", "Bangladesh", "🇧🇩", "+880"),
  barbados("BB", "Barbados", "🇧🇧", "+1-246"),
  belarus("BY", "Belarus", "🇧🇾", "+375"),
  belgium("BE", "Belgium", "🇧🇪", "+32"),
  belize("BZ", "Belize", "🇧🇿", "+501"),
  benin("BJ", "Benin", "🇧🇯", "+229"),
  bhutan("BT", "Bhutan", "🇧🇹", "+975"),
  bolivia("BO", "Bolivia", "🇧🇴", "+591"),
  bosniaHerzegovina("BA", "Bosnia and Herzegovina", "🇧🇦", "+387"),
  botswana("BW", "Botswana", "🇧🇼", "+267"),
  brazil("BR", "Brazil", "🇧🇷", "+55"),
  brunei("BN", "Brunei", "🇧🇳", "+673"),
  bulgaria("BG", "Bulgaria", "🇧🇬", "+359"),
  burkinaFaso("BF", "Burkina Faso", "🇧🇫", "+226"),
  burundi("BI", "Burundi", "🇧🇮", "+257"),
  caboVerde("CV", "Cabo Verde", "🇨🇻", "+238"),
  cambodia("KH", "Cambodia", "🇰🇭", "+855"),
  cameroon("CM", "Cameroon", "🇨🇲", "+237"),
  canada("CA", "Canada", "🇨🇦", "+1"),
  centralAfricanRepublic("CF", "Central African Republic", "🇨🇫", "+236"),
  chad("TD", "Chad", "🇹🇩", "+235"),
  chile("CL", "Chile", "🇨🇱", "+56"),
  china("CN", "China", "🇨🇳", "+86"),
  colombia("CO", "Colombia", "🇨🇴", "+57"),
  comoros("KM", "Comoros", "🇰🇲", "+269"),
  congoBrazzaville("CG", "Congo (Brazzaville)", "🇨🇬", "+242"),
  congoKinshasa("CD", "Congo (Kinshasa)", "🇨🇩", "+243"),
  costaRica("CR", "Costa Rica", "🇨🇷", "+506"),
  croatia("HR", "Croatia", "🇭🇷", "+385"),
  cuba("CU", "Cuba", "🇨🇺", "+53"),
  cyprus("CY", "Cyprus", "🇨🇾", "+357"),
  czechRepublic("CZ", "Czech Republic", "🇨🇿", "+420"),
  denmark("DK", "Denmark", "🇩🇰", "+45"),
  djibouti("DJ", "Djibouti", "🇩🇯", "+253"),
  dominica("DM", "Dominica", "🇩🇲", "+1-767"),
  dominicanRepublic("DO", "Dominican Republic", "🇩🇴", "+1-809"),
  ecuador("EC", "Ecuador", "🇪🇨", "+593"),
  egypt("EG", "Egypt", "🇪🇬", "+20"),
  elSalvador("SV", "El Salvador", "🇸🇻", "+503"),
  equatorialGuinea("GQ", "Equatorial Guinea", "🇬🇶", "+240"),
  eritrea("ER", "Eritrea", "🇪🇷", "+291"),
  estonia("EE", "Estonia", "🇪🇪", "+372"),
  eswatini("SZ", "Eswatini", "🇸🇿", "+268"),
  ethiopia("ET", "Ethiopia", "🇪🇹", "+251"),
  fiji("FJ", "Fiji", "🇫🇯", "+679"),
  finland("FI", "Finland", "🇫🇮", "+358"),
  france("FR", "France", "🇫🇷", "+33"),
  gabon("GA", "Gabon", "🇬🇦", "+241"),
  gambia("GM", "Gambia", "🇬🇲", "+220"),
  georgia("GE", "Georgia", "🇬🇪", "+995"),
  germany("DE", "Germany", "🇩🇪", "+49"),
  ghana("GH", "Ghana", "🇬🇭", "+233"),
  greece("GR", "Greece", "🇬🇷", "+30"),
  grenada("GD", "Grenada", "🇬🇩", "+1-473"),
  guatemala("GT", "Guatemala", "🇬🇹", "+502"),
  guinea("GN", "Guinea", "🇬🇳", "+224"),
  guineaBissau("GW", "Guinea-Bissau", "🇬🇼", "+245"),
  guyana("GY", "Guyana", "🇬🇾", "+592"),
  haiti("HT", "Haiti", "🇭🇹", "+509"),
  honduras("HN", "Honduras", "🇭🇳", "+504"),
  hungary("HU", "Hungary", "🇭🇺", "+36"),
  iceland("IS", "Iceland", "🇮🇸", "+354"),
  india("IN", "India", "🇮🇳", "+91"),
  indonesia("ID", "Indonesia", "🇮🇩", "+62"),
  iran("IR", "Iran", "🇮🇷", "+98"),
  iraq("IQ", "Iraq", "🇮🇶", "+964"),
  ireland("IE", "Ireland", "🇮🇪", "+353"),
  israel("IL", "Israel", "🇮🇱", "+972"),
  italy("IT", "Italy", "🇮🇹", "+39"),
  jamaica("JM", "Jamaica", "🇯🇲", "+1-876"),
  japan("JP", "Japan", "🇯🇵", "+81"),
  jordan("JO", "Jordan", "🇯🇴", "+962"),
  kazakhstan("KZ", "Kazakhstan", "🇰🇿", "+7"),
  kenya("KE", "Kenya", "🇰🇪", "+254"),
  kiribati("KI", "Kiribati", "🇰🇮", "+686"),
  koreaNorth("KP", "North Korea", "🇰🇵", "+850"),
  koreaSouth("KR", "South Korea", "🇰🇷", "+82"),
  kuwait("KW", "Kuwait", "🇰🇼", "+965"),
  kyrgyzstan("KG", "Kyrgyzstan", "🇰🇬", "+996"),
  laos("LA", "Laos", "🇱🇦", "+856"),
  latvia("LV", "Latvia", "🇱🇻", "+371"),
  lebanon("LB", "Lebanon", "🇱🇧", "+961"),
  lesotho("LS", "Lesotho", "🇱🇸", "+266"),
  liberia("LR", "Liberia", "🇱🇷", "+231"),
  libya("LY", "Libya", "🇱🇾", "+218"),
  liechtenstein("LI", "Liechtenstein", "🇱🇮", "+423"),
  lithuania("LT", "Lithuania", "🇱🇹", "+370"),
  luxembourg("LU", "Luxembourg", "🇱🇺", "+352"),
  madagascar("MG", "Madagascar", "🇲🇬", "+261"),
  malawi("MW", "Malawi", "🇲🇼", "+265"),
  malaysia("MY", "Malaysia", "🇲🇾", "+60"),
  maldives("MV", "Maldives", "🇲🇻", "+960"),
  mali("ML", "Mali", "🇲🇱", "+223"),
  malta("MT", "Malta", "🇲🇹", "+356"),
  marshallIslands("MH", "Marshall Islands", "🇲🇭", "+692"),
  mauritania("MR", "Mauritania", "🇲🇷", "+222"),
  mauritius("MU", "Mauritius", "🇲🇺", "+230"),
  mexico("MX", "Mexico", "🇲🇽", "+52"),
  micronesia("FM", "Micronesia", "🇫🇲", "+691"),
  moldova("MD", "Moldova", "🇲🇩", "+373"),
  monaco("MC", "Monaco", "🇲🇨", "+377"),
  mongolia("MN", "Mongolia", "🇲🇳", "+976"),
  montenegro("ME", "Montenegro", "🇲🇪", "+382"),
  morocco("MA", "Morocco", "🇲🇦", "+212"),
  mozambique("MZ", "Mozambique", "🇲🇿", "+258"),
  myanmar("MM", "Myanmar", "🇲🇲", "+95"),
  namibia("NA", "Namibia", "🇳🇦", "+264"),
  nauru("NR", "Nauru", "🇳🇷", "+674"),
  nepal("NP", "Nepal", "🇳🇵", "+977"),
  netherlands("NL", "Netherlands", "🇳🇱", "+31"),
  newZealand("NZ", "New Zealand", "🇳🇿", "+64"),
  nicaragua("NI", "Nicaragua", "🇳🇮", "+505"),
  niger("NE", "Niger", "🇳🇪", "+227"),
  nigeria("NG", "Nigeria", "🇳🇬", "+234"),
  northMacedonia("MK", "North Macedonia", "🇲🇰", "+389"),
  norway("NO", "Norway", "🇳🇴", "+47"),
  oman("OM", "Oman", "🇴🇲", "+968"),
  pakistan("PK", "Pakistan", "🇵🇰", "+92"),
  palau("PW", "Palau", "🇵🇼", "+680"),
  panama("PA", "Panama", "🇵🇦", "+507"),
  papuaNewGuinea("PG", "Papua New Guinea", "🇵🇬", "+675"),
  paraguay("PY", "Paraguay", "🇵🇾", "+595"),
  peru("PE", "Peru", "🇵🇪", "+51"),
  philippines("PH", "Philippines", "🇵🇭", "+63"),
  poland("PL", "Poland", "🇵🇱", "+48"),
  portugal("PT", "Portugal", "🇵🇹", "+351"),
  qatar("QA", "Qatar", "🇶🇦", "+974"),
  romania("RO", "Romania", "🇷🇴", "+40"),
  russia("RU", "Russia", "🇷🇺", "+7"),
  rwanda("RW", "Rwanda", "🇷🇼", "+250"),
  saintKittsNevis("KN", "Saint Kitts and Nevis", "🇰🇳", "+1-869"),
  saintLucia("LC", "Saint Lucia", "🇱🇨", "+1-758"),
  saintVincentGrenadines("VC", "Saint Vincent and the Grenadines", "🇻🇨", "+1-784"),
  samoa("WS", "Samoa", "🇼🇸", "+685"),
  sanMarino("SM", "San Marino", "🇸🇲", "+378"),
  saoTomePrincipe("ST", "Sao Tome and Principe", "🇸🇹", "+239"),
  saudiArabia("SA", "Saudi Arabia", "🇸🇦", "+966"),
  senegal("SN", "Senegal", "🇸🇳", "+221"),
  serbia("RS", "Serbia", "🇷🇸", "+381"),
  seychelles("SC", "Seychelles", "🇸🇨", "+248"),
  sierraLeone("SL", "Sierra Leone", "🇸🇱", "+232"),
  singapore("SG", "Singapore", "🇸🇬", "+65"),
  slovakia("SK", "Slovakia", "🇸🇰", "+421"),
  slovenia("SI", "Slovenia", "🇸🇮", "+386"),
  solomonIslands("SB", "Solomon Islands", "🇸🇧", "+677"),
  somalia("SO", "Somalia", "🇸🇴", "+252"),
  southAfrica("ZA", "South Africa", "🇿🇦", "+27"),
  southSudan("SS", "South Sudan", "🇸🇸", "+211"),
  spain("ES", "Spain", "🇪🇸", "+34"),
  sriLanka("LK", "Sri Lanka", "🇱🇰", "+94"),
  sudan("SD", "Sudan", "🇸🇩", "+249"),
  suriname("SR", "Suriname", "🇸🇷", "+597"),
  sweden("SE", "Sweden", "🇸🇪", "+46"),
  switzerland("CH", "Switzerland", "🇨🇭", "+41"),
  syria("SY", "Syria", "🇸🇾", "+963"),
  taiwan("TW", "Taiwan", "🇹🇼", "+886"),
  tajikistan("TJ", "Tajikistan", "🇹🇯", "+992"),
  tanzania("TZ", "Tanzania", "🇹🇿", "+255"),
  thailand("TH", "Thailand", "🇹🇭", "+66"),
  timorLeste("TL", "Timor-Leste", "🇹🇱", "+670"),
  togo("TG", "Togo", "🇹🇬", "+228"),
  tonga("TO", "Tonga", "🇹🇴", "+676"),
  trinidadTobago("TT", "Trinidad and Tobago", "🇹🇹", "+1-868"),
  tunisia("TN", "Tunisia", "🇹🇳", "+216"),
  turkey("TR", "Turkey", "🇹🇷", "+90"),
  turkmenistan("TM", "Turkmenistan", "🇹🇲", "+993"),
  tuvalu("TV", "Tuvalu", "🇹🇻", "+688"),
  uganda("UG", "Uganda", "🇺🇬", "+256"),
  ukraine("UA", "Ukraine", "🇺🇦", "+380"),
  unitedArabEmirates("AE", "United Arab Emirates", "🇦🇪", "+971"),
  unitedKingdom("GB", "United Kingdom", "🇬🇧", "+44"),
  unitedStates("US", "United States", "🇺🇸", "+1"),
  uruguay("UY", "Uruguay", "🇺🇾", "+598"),
  uzbekistan("UZ", "Uzbekistan", "🇺🇿", "+998"),
  vanuatu("VU", "Vanuatu", "🇻🇺", "+678"),
  venezuela("VE", "Venezuela", "🇻🇪", "+58"),
  vietnam("VN", "Vietnam", "🇻🇳", "+84"),
  yemen("YE", "Yemen", "🇾🇪", "+967"),
  zambia("ZM", "Zambia", "🇿🇲", "+260"),
  zimbabwe("ZW", "Zimbabwe", "🇿🇼", "+263");

  final String code;
  final String name;
  final String flag;
  final String dialCode;

  const AppCountry(this.code, this.name, this.flag, this.dialCode);

  String get displayName => "$flag $name ($dialCode)";
}
