// Mocks generated by Mockito 5.4.4 from annotations
// in student_management/test/presentation/views/student/presentation/manager/student_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:student_management/core/base/paginated_response.dart' as _i5;
import 'package:student_management/presentation/views/student/data/models/student_model.dart'
    as _i2;
import 'package:student_management/presentation/views/student/data/repositories/student_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStudentResponse_0 extends _i1.SmartFake
    implements _i2.StudentResponse {
  _FakeStudentResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStudentStatistics_1 extends _i1.SmartFake
    implements _i2.StudentStatistics {
  _FakeStudentStatistics_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StudentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStudentRepository extends _i1.Mock implements _i3.StudentRepository {
  MockStudentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.PaginatedResponse<_i2.StudentResponse>> getAllStudents({
    int page = 0,
    int size = 20,
    String? classId,
    String? sectionId,
    String? status,
    String? search,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllStudents,
          [],
          {
            #page: page,
            #size: size,
            #classId: classId,
            #sectionId: sectionId,
            #status: status,
            #search: search,
          },
        ),
        returnValue: _i4.Future<_i5.PaginatedResponse<_i2.StudentResponse>>.value(
            _i5.PaginatedResponse<_i2.StudentResponse>.fromList(
                <_i2.StudentResponse>[])),
      ) as _i4.Future<_i5.PaginatedResponse<_i2.StudentResponse>>);

  @override
  _i4.Future<_i2.StudentResponse> getStudentById(String? studentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStudentById,
          [studentId],
        ),
        returnValue:
            _i4.Future<_i2.StudentResponse>.value(_FakeStudentResponse_0(
          this,
          Invocation.method(
            #getStudentById,
            [studentId],
          ),
        )),
      ) as _i4.Future<_i2.StudentResponse>);

  @override
  _i4.Future<_i2.StudentResponse> createStudent(
          _i2.CreateStudentRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStudent,
          [request],
        ),
        returnValue:
            _i4.Future<_i2.StudentResponse>.value(_FakeStudentResponse_0(
          this,
          Invocation.method(
            #createStudent,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.StudentResponse>);

  @override
  _i4.Future<_i2.StudentResponse> updateStudent(
    String? studentId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStudent,
          [
            studentId,
            updates,
          ],
        ),
        returnValue:
            _i4.Future<_i2.StudentResponse>.value(_FakeStudentResponse_0(
          this,
          Invocation.method(
            #updateStudent,
            [
              studentId,
              updates,
            ],
          ),
        )),
      ) as _i4.Future<_i2.StudentResponse>);

  @override
  _i4.Future<void> deleteStudent(String? studentId) => (super.noSuchMethod(
        Invocation.method(
          #deleteStudent,
          [studentId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateStudentStatus(
    String? studentId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStudentStatus,
          [
            studentId,
            status,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.StudentStatistics> getStatistics() => (super.noSuchMethod(
        Invocation.method(
          #getStatistics,
          [],
        ),
        returnValue:
            _i4.Future<_i2.StudentStatistics>.value(_FakeStudentStatistics_1(
          this,
          Invocation.method(
            #getStatistics,
            [],
          ),
        )),
      ) as _i4.Future<_i2.StudentStatistics>);

  @override
  _i4.Future<List<_i2.StudentResponse>> getStudentsByClass(String? classId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStudentsByClass,
          [classId],
        ),
        returnValue: _i4.Future<List<_i2.StudentResponse>>.value(
            <_i2.StudentResponse>[]),
      ) as _i4.Future<List<_i2.StudentResponse>>);

  @override
  _i4.Future<List<_i2.StudentResponse>> searchStudents(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchStudents,
          [query],
        ),
        returnValue: _i4.Future<List<_i2.StudentResponse>>.value(
            <_i2.StudentResponse>[]),
      ) as _i4.Future<List<_i2.StudentResponse>>);
}
