// Mocks generated by Mockito 5.4.4 from annotations
// in student_management/test/presentation/views/notification/presentation/manager/notification_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:student_management/presentation/views/notification/data/models/notification_model.dart'
    as _i2;
import 'package:student_management/presentation/views/notification/data/repositories/notification_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotificationResponse_0 extends _i1.SmartFake
    implements _i2.NotificationResponse {
  _FakeNotificationResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i3.NotificationRepository {
  MockNotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.NotificationResponse>> getMyNotifications({
    int? page,
    int? size,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyNotifications,
          [],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i4.Future<List<_i2.NotificationResponse>>.value(
            <_i2.NotificationResponse>[]),
      ) as _i4.Future<List<_i2.NotificationResponse>>);

  @override
  _i4.Future<List<_i2.NotificationResponse>> getUnreadNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnreadNotifications,
          [],
        ),
        returnValue: _i4.Future<List<_i2.NotificationResponse>>.value(
            <_i2.NotificationResponse>[]),
      ) as _i4.Future<List<_i2.NotificationResponse>>);

  @override
  _i4.Future<int> getUnreadCount() => (super.noSuchMethod(
        Invocation.method(
          #getUnreadCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> markAsRead(String? notificationId) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [notificationId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markAllAsRead() => (super.noSuchMethod(
        Invocation.method(
          #markAllAsRead,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.NotificationResponse> sendNotification(
          _i2.SendNotificationRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendNotification,
          [request],
        ),
        returnValue: _i4.Future<_i2.NotificationResponse>.value(
            _FakeNotificationResponse_0(
          this,
          Invocation.method(
            #sendNotification,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.NotificationResponse>);
}
