// Mocks generated by Mockito 5.4.4 from annotations
// in student_management/test/presentation/views/leave/presentation/manager/leave_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:student_management/presentation/views/leave/data/models/leave_balance_model.dart'
    as _i4;
import 'package:student_management/presentation/views/leave/data/models/leave_request_model.dart'
    as _i3;
import 'package:student_management/presentation/views/leave/data/models/leave_type_model.dart'
    as _i2;
import 'package:student_management/presentation/views/leave/data/repositories/leave_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLeaveTypeResponse_0 extends _i1.SmartFake
    implements _i2.LeaveTypeResponse {
  _FakeLeaveTypeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLeaveRequestResponse_1 extends _i1.SmartFake
    implements _i3.LeaveRequestResponse {
  _FakeLeaveRequestResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLeaveBalanceResponse_2 extends _i1.SmartFake
    implements _i4.LeaveBalanceResponse {
  _FakeLeaveBalanceResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLeaveSummaryResponse_3 extends _i1.SmartFake
    implements _i4.LeaveSummaryResponse {
  _FakeLeaveSummaryResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LeaveRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLeaveRepository extends _i1.Mock implements _i5.LeaveRepository {
  MockLeaveRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.LeaveTypeResponse>> getLeaveTypes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLeaveTypes,
          [],
        ),
        returnValue: _i6.Future<List<_i2.LeaveTypeResponse>>.value(
            <_i2.LeaveTypeResponse>[]),
      ) as _i6.Future<List<_i2.LeaveTypeResponse>>);

  @override
  _i6.Future<List<_i2.LeaveTypeResponse>> getActiveLeaveTypes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveLeaveTypes,
          [],
        ),
        returnValue: _i6.Future<List<_i2.LeaveTypeResponse>>.value(
            <_i2.LeaveTypeResponse>[]),
      ) as _i6.Future<List<_i2.LeaveTypeResponse>>);

  @override
  _i6.Future<_i2.LeaveTypeResponse> createLeaveType(
          _i2.LeaveTypeRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createLeaveType,
          [request],
        ),
        returnValue:
            _i6.Future<_i2.LeaveTypeResponse>.value(_FakeLeaveTypeResponse_0(
          this,
          Invocation.method(
            #createLeaveType,
            [request],
          ),
        )),
      ) as _i6.Future<_i2.LeaveTypeResponse>);

  @override
  _i6.Future<_i2.LeaveTypeResponse> updateLeaveType(
    String? id,
    _i2.LeaveTypeRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLeaveType,
          [
            id,
            request,
          ],
        ),
        returnValue:
            _i6.Future<_i2.LeaveTypeResponse>.value(_FakeLeaveTypeResponse_0(
          this,
          Invocation.method(
            #updateLeaveType,
            [
              id,
              request,
            ],
          ),
        )),
      ) as _i6.Future<_i2.LeaveTypeResponse>);

  @override
  _i6.Future<void> deleteLeaveType(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteLeaveType,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.LeaveRequestResponse> applyLeave(
          _i3.LeaveRequestCreate? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #applyLeave,
          [request],
        ),
        returnValue: _i6.Future<_i3.LeaveRequestResponse>.value(
            _FakeLeaveRequestResponse_1(
          this,
          Invocation.method(
            #applyLeave,
            [request],
          ),
        )),
      ) as _i6.Future<_i3.LeaveRequestResponse>);

  @override
  _i6.Future<List<_i3.LeaveRequestResponse>> getMyLeaves() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyLeaves,
          [],
        ),
        returnValue: _i6.Future<List<_i3.LeaveRequestResponse>>.value(
            <_i3.LeaveRequestResponse>[]),
      ) as _i6.Future<List<_i3.LeaveRequestResponse>>);

  @override
  _i6.Future<List<_i3.LeaveRequestResponse>> getPendingApprovals() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingApprovals,
          [],
        ),
        returnValue: _i6.Future<List<_i3.LeaveRequestResponse>>.value(
            <_i3.LeaveRequestResponse>[]),
      ) as _i6.Future<List<_i3.LeaveRequestResponse>>);

  @override
  _i6.Future<List<_i3.LeaveRequestResponse>> getAllLeaveRequests({
    int? page,
    int? size,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllLeaveRequests,
          [],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i6.Future<List<_i3.LeaveRequestResponse>>.value(
            <_i3.LeaveRequestResponse>[]),
      ) as _i6.Future<List<_i3.LeaveRequestResponse>>);

  @override
  _i6.Future<_i3.LeaveRequestResponse> approveLeave(
    String? id, {
    String? remarks,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #approveLeave,
          [id],
          {#remarks: remarks},
        ),
        returnValue: _i6.Future<_i3.LeaveRequestResponse>.value(
            _FakeLeaveRequestResponse_1(
          this,
          Invocation.method(
            #approveLeave,
            [id],
            {#remarks: remarks},
          ),
        )),
      ) as _i6.Future<_i3.LeaveRequestResponse>);

  @override
  _i6.Future<_i3.LeaveRequestResponse> rejectLeave(
    String? id, {
    String? remarks,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rejectLeave,
          [id],
          {#remarks: remarks},
        ),
        returnValue: _i6.Future<_i3.LeaveRequestResponse>.value(
            _FakeLeaveRequestResponse_1(
          this,
          Invocation.method(
            #rejectLeave,
            [id],
            {#remarks: remarks},
          ),
        )),
      ) as _i6.Future<_i3.LeaveRequestResponse>);

  @override
  _i6.Future<_i3.LeaveRequestResponse> cancelLeave(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelLeave,
          [id],
        ),
        returnValue: _i6.Future<_i3.LeaveRequestResponse>.value(
            _FakeLeaveRequestResponse_1(
          this,
          Invocation.method(
            #cancelLeave,
            [id],
          ),
        )),
      ) as _i6.Future<_i3.LeaveRequestResponse>);

  @override
  _i6.Future<List<_i4.LeaveBalanceResponse>> getMyBalance(
          {String? academicYear}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyBalance,
          [],
          {#academicYear: academicYear},
        ),
        returnValue: _i6.Future<List<_i4.LeaveBalanceResponse>>.value(
            <_i4.LeaveBalanceResponse>[]),
      ) as _i6.Future<List<_i4.LeaveBalanceResponse>>);

  @override
  _i6.Future<List<_i4.LeaveBalanceResponse>> getUserBalance(
    String? userId, {
    String? academicYear,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserBalance,
          [userId],
          {#academicYear: academicYear},
        ),
        returnValue: _i6.Future<List<_i4.LeaveBalanceResponse>>.value(
            <_i4.LeaveBalanceResponse>[]),
      ) as _i6.Future<List<_i4.LeaveBalanceResponse>>);

  @override
  _i6.Future<_i4.LeaveBalanceResponse> initializeBalance(
    String? userId,
    String? leaveTypeId,
    String? academicYear,
    int? totalDays,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #initializeBalance,
          [
            userId,
            leaveTypeId,
            academicYear,
            totalDays,
          ],
        ),
        returnValue: _i6.Future<_i4.LeaveBalanceResponse>.value(
            _FakeLeaveBalanceResponse_2(
          this,
          Invocation.method(
            #initializeBalance,
            [
              userId,
              leaveTypeId,
              academicYear,
              totalDays,
            ],
          ),
        )),
      ) as _i6.Future<_i4.LeaveBalanceResponse>);

  @override
  _i6.Future<_i4.LeaveSummaryResponse> getMySummary() => (super.noSuchMethod(
        Invocation.method(
          #getMySummary,
          [],
        ),
        returnValue: _i6.Future<_i4.LeaveSummaryResponse>.value(
            _FakeLeaveSummaryResponse_3(
          this,
          Invocation.method(
            #getMySummary,
            [],
          ),
        )),
      ) as _i6.Future<_i4.LeaveSummaryResponse>);

  @override
  _i6.Future<_i4.LeaveSummaryResponse> getUserSummary(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserSummary,
          [userId],
        ),
        returnValue: _i6.Future<_i4.LeaveSummaryResponse>.value(
            _FakeLeaveSummaryResponse_3(
          this,
          Invocation.method(
            #getUserSummary,
            [userId],
          ),
        )),
      ) as _i6.Future<_i4.LeaveSummaryResponse>);
}
