// Mocks generated by Mockito 5.4.4 from annotations
// in student_management/test/presentation/views/fee/presentation/manager/fee_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:student_management/presentation/views/fee/data/models/fee_payment_model.dart'
    as _i4;
import 'package:student_management/presentation/views/fee/data/models/fee_structure_model.dart'
    as _i3;
import 'package:student_management/presentation/views/fee/data/models/fee_type_model.dart'
    as _i2;
import 'package:student_management/presentation/views/fee/data/repositories/fee_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFeeTypeResponse_0 extends _i1.SmartFake
    implements _i2.FeeTypeResponse {
  _FakeFeeTypeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFeeStructureResponse_1 extends _i1.SmartFake
    implements _i3.FeeStructureResponse {
  _FakeFeeStructureResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFeePaymentResponse_2 extends _i1.SmartFake
    implements _i4.FeePaymentResponse {
  _FakeFeePaymentResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCollectionReport_3 extends _i1.SmartFake
    implements _i4.CollectionReport {
  _FakeCollectionReport_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FeeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeeRepository extends _i1.Mock implements _i5.FeeRepository {
  MockFeeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.FeeTypeResponse>> getFeeTypes() => (super.noSuchMethod(
        Invocation.method(
          #getFeeTypes,
          [],
        ),
        returnValue: _i6.Future<List<_i2.FeeTypeResponse>>.value(
            <_i2.FeeTypeResponse>[]),
      ) as _i6.Future<List<_i2.FeeTypeResponse>>);

  @override
  _i6.Future<List<_i2.FeeTypeResponse>> getActiveFeeTypes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveFeeTypes,
          [],
        ),
        returnValue: _i6.Future<List<_i2.FeeTypeResponse>>.value(
            <_i2.FeeTypeResponse>[]),
      ) as _i6.Future<List<_i2.FeeTypeResponse>>);

  @override
  _i6.Future<_i2.FeeTypeResponse> createFeeType(_i2.FeeTypeRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFeeType,
          [request],
        ),
        returnValue:
            _i6.Future<_i2.FeeTypeResponse>.value(_FakeFeeTypeResponse_0(
          this,
          Invocation.method(
            #createFeeType,
            [request],
          ),
        )),
      ) as _i6.Future<_i2.FeeTypeResponse>);

  @override
  _i6.Future<_i2.FeeTypeResponse> updateFeeType(
    String? id,
    _i2.FeeTypeRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFeeType,
          [
            id,
            request,
          ],
        ),
        returnValue:
            _i6.Future<_i2.FeeTypeResponse>.value(_FakeFeeTypeResponse_0(
          this,
          Invocation.method(
            #updateFeeType,
            [
              id,
              request,
            ],
          ),
        )),
      ) as _i6.Future<_i2.FeeTypeResponse>);

  @override
  _i6.Future<void> deleteFeeType(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteFeeType,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.FeeStructureResponse>> getFeeStructures() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeeStructures,
          [],
        ),
        returnValue: _i6.Future<List<_i3.FeeStructureResponse>>.value(
            <_i3.FeeStructureResponse>[]),
      ) as _i6.Future<List<_i3.FeeStructureResponse>>);

  @override
  _i6.Future<List<_i3.FeeStructureResponse>> getFeeStructuresByClass(
          String? classId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeeStructuresByClass,
          [classId],
        ),
        returnValue: _i6.Future<List<_i3.FeeStructureResponse>>.value(
            <_i3.FeeStructureResponse>[]),
      ) as _i6.Future<List<_i3.FeeStructureResponse>>);

  @override
  _i6.Future<_i3.FeeStructureResponse> createFeeStructure(
          _i3.FeeStructureRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFeeStructure,
          [request],
        ),
        returnValue: _i6.Future<_i3.FeeStructureResponse>.value(
            _FakeFeeStructureResponse_1(
          this,
          Invocation.method(
            #createFeeStructure,
            [request],
          ),
        )),
      ) as _i6.Future<_i3.FeeStructureResponse>);

  @override
  _i6.Future<_i3.FeeStructureResponse> updateFeeStructure(
    String? id,
    _i3.FeeStructureRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFeeStructure,
          [
            id,
            request,
          ],
        ),
        returnValue: _i6.Future<_i3.FeeStructureResponse>.value(
            _FakeFeeStructureResponse_1(
          this,
          Invocation.method(
            #updateFeeStructure,
            [
              id,
              request,
            ],
          ),
        )),
      ) as _i6.Future<_i3.FeeStructureResponse>);

  @override
  _i6.Future<_i4.FeePaymentResponse> collectFee(
          _i4.FeePaymentRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #collectFee,
          [request],
        ),
        returnValue:
            _i6.Future<_i4.FeePaymentResponse>.value(_FakeFeePaymentResponse_2(
          this,
          Invocation.method(
            #collectFee,
            [request],
          ),
        )),
      ) as _i6.Future<_i4.FeePaymentResponse>);

  @override
  _i6.Future<List<_i4.FeePaymentResponse>> getStudentPayments(
          String? studentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStudentPayments,
          [studentId],
        ),
        returnValue: _i6.Future<List<_i4.FeePaymentResponse>>.value(
            <_i4.FeePaymentResponse>[]),
      ) as _i6.Future<List<_i4.FeePaymentResponse>>);

  @override
  _i6.Future<List<_i4.FeePaymentResponse>> getStudentPendingFees(
          String? studentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStudentPendingFees,
          [studentId],
        ),
        returnValue: _i6.Future<List<_i4.FeePaymentResponse>>.value(
            <_i4.FeePaymentResponse>[]),
      ) as _i6.Future<List<_i4.FeePaymentResponse>>);

  @override
  _i6.Future<List<_i4.FeePaymentResponse>> getAllPayments({
    int? page,
    int? size,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllPayments,
          [],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue: _i6.Future<List<_i4.FeePaymentResponse>>.value(
            <_i4.FeePaymentResponse>[]),
      ) as _i6.Future<List<_i4.FeePaymentResponse>>);

  @override
  _i6.Future<_i4.FeePaymentResponse> getReceipt(String? paymentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReceipt,
          [paymentId],
        ),
        returnValue:
            _i6.Future<_i4.FeePaymentResponse>.value(_FakeFeePaymentResponse_2(
          this,
          Invocation.method(
            #getReceipt,
            [paymentId],
          ),
        )),
      ) as _i6.Future<_i4.FeePaymentResponse>);

  @override
  _i6.Future<List<_i4.FeePaymentResponse>> getOverduePayments() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOverduePayments,
          [],
        ),
        returnValue: _i6.Future<List<_i4.FeePaymentResponse>>.value(
            <_i4.FeePaymentResponse>[]),
      ) as _i6.Future<List<_i4.FeePaymentResponse>>);

  @override
  _i6.Future<_i4.CollectionReport> getCollectionReport() => (super.noSuchMethod(
        Invocation.method(
          #getCollectionReport,
          [],
        ),
        returnValue:
            _i6.Future<_i4.CollectionReport>.value(_FakeCollectionReport_3(
          this,
          Invocation.method(
            #getCollectionReport,
            [],
          ),
        )),
      ) as _i6.Future<_i4.CollectionReport>);
}
