// Mocks generated by Mockito 5.4.4 from annotations
// in student_management/test/presentation/views/exam/presentation/manager/exam_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:student_management/presentation/views/exam/data/models/exam_model.dart'
    as _i3;
import 'package:student_management/presentation/views/exam/data/models/exam_result_model.dart'
    as _i4;
import 'package:student_management/presentation/views/exam/data/models/exam_type_model.dart'
    as _i2;
import 'package:student_management/presentation/views/exam/data/repositories/exam_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExamTypeResponse_0 extends _i1.SmartFake
    implements _i2.ExamTypeResponse {
  _FakeExamTypeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExamResponse_1 extends _i1.SmartFake implements _i3.ExamResponse {
  _FakeExamResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExamResultResponse_2 extends _i1.SmartFake
    implements _i4.ExamResultResponse {
  _FakeExamResultResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExamStatistics_3 extends _i1.SmartFake
    implements _i4.ExamStatistics {
  _FakeExamStatistics_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReportCard_4 extends _i1.SmartFake implements _i4.ReportCard {
  _FakeReportCard_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ExamRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExamRepository extends _i1.Mock implements _i5.ExamRepository {
  MockExamRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.ExamTypeResponse>> getExamTypes() => (super.noSuchMethod(
        Invocation.method(
          #getExamTypes,
          [],
        ),
        returnValue: _i6.Future<List<_i2.ExamTypeResponse>>.value(
            <_i2.ExamTypeResponse>[]),
      ) as _i6.Future<List<_i2.ExamTypeResponse>>);

  @override
  _i6.Future<List<_i2.ExamTypeResponse>> getActiveExamTypes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveExamTypes,
          [],
        ),
        returnValue: _i6.Future<List<_i2.ExamTypeResponse>>.value(
            <_i2.ExamTypeResponse>[]),
      ) as _i6.Future<List<_i2.ExamTypeResponse>>);

  @override
  _i6.Future<_i2.ExamTypeResponse> createExamType(
          _i2.ExamTypeRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createExamType,
          [request],
        ),
        returnValue:
            _i6.Future<_i2.ExamTypeResponse>.value(_FakeExamTypeResponse_0(
          this,
          Invocation.method(
            #createExamType,
            [request],
          ),
        )),
      ) as _i6.Future<_i2.ExamTypeResponse>);

  @override
  _i6.Future<_i2.ExamTypeResponse> updateExamType(
    String? id,
    _i2.ExamTypeRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExamType,
          [
            id,
            request,
          ],
        ),
        returnValue:
            _i6.Future<_i2.ExamTypeResponse>.value(_FakeExamTypeResponse_0(
          this,
          Invocation.method(
            #updateExamType,
            [
              id,
              request,
            ],
          ),
        )),
      ) as _i6.Future<_i2.ExamTypeResponse>);

  @override
  _i6.Future<void> deleteExamType(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteExamType,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i3.ExamResponse>> getExams({
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExams,
          [],
          {
            #page: page,
            #size: size,
          },
        ),
        returnValue:
            _i6.Future<List<_i3.ExamResponse>>.value(<_i3.ExamResponse>[]),
      ) as _i6.Future<List<_i3.ExamResponse>>);

  @override
  _i6.Future<_i3.ExamResponse> getExamById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getExamById,
          [id],
        ),
        returnValue: _i6.Future<_i3.ExamResponse>.value(_FakeExamResponse_1(
          this,
          Invocation.method(
            #getExamById,
            [id],
          ),
        )),
      ) as _i6.Future<_i3.ExamResponse>);

  @override
  _i6.Future<List<_i3.ExamResponse>> getExamsByClass(String? classId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExamsByClass,
          [classId],
        ),
        returnValue:
            _i6.Future<List<_i3.ExamResponse>>.value(<_i3.ExamResponse>[]),
      ) as _i6.Future<List<_i3.ExamResponse>>);

  @override
  _i6.Future<List<_i3.ExamResponse>> getUpcomingExams() => (super.noSuchMethod(
        Invocation.method(
          #getUpcomingExams,
          [],
        ),
        returnValue:
            _i6.Future<List<_i3.ExamResponse>>.value(<_i3.ExamResponse>[]),
      ) as _i6.Future<List<_i3.ExamResponse>>);

  @override
  _i6.Future<List<_i3.ExamResponse>> getUpcomingExamsByClass(String? classId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUpcomingExamsByClass,
          [classId],
        ),
        returnValue:
            _i6.Future<List<_i3.ExamResponse>>.value(<_i3.ExamResponse>[]),
      ) as _i6.Future<List<_i3.ExamResponse>>);

  @override
  _i6.Future<_i3.ExamResponse> createExam(_i3.ExamRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createExam,
          [request],
        ),
        returnValue: _i6.Future<_i3.ExamResponse>.value(_FakeExamResponse_1(
          this,
          Invocation.method(
            #createExam,
            [request],
          ),
        )),
      ) as _i6.Future<_i3.ExamResponse>);

  @override
  _i6.Future<_i3.ExamResponse> updateExam(
    String? id,
    _i3.ExamRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExam,
          [
            id,
            request,
          ],
        ),
        returnValue: _i6.Future<_i3.ExamResponse>.value(_FakeExamResponse_1(
          this,
          Invocation.method(
            #updateExam,
            [
              id,
              request,
            ],
          ),
        )),
      ) as _i6.Future<_i3.ExamResponse>);

  @override
  _i6.Future<void> deleteExam(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteExam,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.ExamResultResponse> enterMarks(
    String? examId,
    _i4.ExamResultRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #enterMarks,
          [
            examId,
            request,
          ],
        ),
        returnValue:
            _i6.Future<_i4.ExamResultResponse>.value(_FakeExamResultResponse_2(
          this,
          Invocation.method(
            #enterMarks,
            [
              examId,
              request,
            ],
          ),
        )),
      ) as _i6.Future<_i4.ExamResultResponse>);

  @override
  _i6.Future<List<_i4.ExamResultResponse>> enterBulkMarks(
    String? examId,
    List<_i4.ExamResultRequest>? requests,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #enterBulkMarks,
          [
            examId,
            requests,
          ],
        ),
        returnValue: _i6.Future<List<_i4.ExamResultResponse>>.value(
            <_i4.ExamResultResponse>[]),
      ) as _i6.Future<List<_i4.ExamResultResponse>>);

  @override
  _i6.Future<List<_i4.ExamResultResponse>> getExamResults(String? examId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExamResults,
          [examId],
        ),
        returnValue: _i6.Future<List<_i4.ExamResultResponse>>.value(
            <_i4.ExamResultResponse>[]),
      ) as _i6.Future<List<_i4.ExamResultResponse>>);

  @override
  _i6.Future<_i4.ExamStatistics> getExamStatistics(String? examId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExamStatistics,
          [examId],
        ),
        returnValue: _i6.Future<_i4.ExamStatistics>.value(_FakeExamStatistics_3(
          this,
          Invocation.method(
            #getExamStatistics,
            [examId],
          ),
        )),
      ) as _i6.Future<_i4.ExamStatistics>);

  @override
  _i6.Future<List<_i4.ExamResultResponse>> getStudentResults(
          String? studentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStudentResults,
          [studentId],
        ),
        returnValue: _i6.Future<List<_i4.ExamResultResponse>>.value(
            <_i4.ExamResultResponse>[]),
      ) as _i6.Future<List<_i4.ExamResultResponse>>);

  @override
  _i6.Future<_i4.ReportCard> getReportCard(String? studentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReportCard,
          [studentId],
        ),
        returnValue: _i6.Future<_i4.ReportCard>.value(_FakeReportCard_4(
          this,
          Invocation.method(
            #getReportCard,
            [studentId],
          ),
        )),
      ) as _i6.Future<_i4.ReportCard>);
}
